import type { Locale } from "@/lib/i18n";

const labels: Partial<Record<Locale, Record<string, string>>> = {
  fr: {
    "ceramics.wheel_throwing": "Tournage au tour",
    "ceramics.hand_building": "Façonnage à la main",
    "ceramics.glazing": "Émaillage céramique",
    "ceramics.firing": "Cuisson au four",
    "wood.joinery": "Assemblage bois",
    "wood.carving": "Sculpture sur bois",
    "wood.furniture_making": "Fabrication de meubles",
    "textiles.weaving": "Tissage",
    "textiles.embroidery": "Broderie",
    "textiles.sewing": "Couture",
    "metal.smithing": "Forge",
    "metal.fabrication": "Fabrication métallique",
    "glass.forming": "Mise en forme du verre",
    "jewellery.making": "Fabrication de bijoux",
    "restoration.conservation": "Conservation",
    "restoration.repair": "Réparation-restauration",
    "stone.carving": "Sculpture sur pierre",
    "leather.construction": "Fabrication en cuir",
  },
  de: {
    "ceramics.wheel_throwing": "Drehen auf der Töpferscheibe",
    "ceramics.hand_building": "Freies Formen von Hand",
    "ceramics.glazing": "Keramikglasur",
    "ceramics.firing": "Brennen im Ofen",
    "wood.joinery": "Holzverbindungen",
    "wood.carving": "Holzschnitzen",
    "wood.furniture_making": "Möbelbau",
    "textiles.weaving": "Weben",
    "textiles.embroidery": "Sticken",
    "textiles.sewing": "Nähen",
    "metal.smithing": "Schmieden",
    "metal.fabrication": "Metallverarbeitung",
    "glass.forming": "Glasformung",
    "jewellery.making": "Schmuckherstellung",
    "restoration.conservation": "Konservierung",
    "restoration.repair": "Restauratorische Reparatur",
    "stone.carving": "Steinbildhauerei",
    "leather.construction": "Lederverarbeitung",
  },
  nl: {
    "ceramics.wheel_throwing": "Draaien op de pottenbakkersschijf",
    "ceramics.hand_building": "Handopbouw",
    "ceramics.glazing": "Keramisch glazuren",
    "ceramics.firing": "Ovenstoken",
    "wood.joinery": "Houtverbindingen",
    "wood.carving": "Houtsnijden",
    "wood.furniture_making": "Meubelmakerij",
    "textiles.weaving": "Weven",
    "textiles.embroidery": "Borduren",
    "textiles.sewing": "Naaien",
    "metal.smithing": "Smeden",
    "metal.fabrication": "Metaalbewerking",
    "glass.forming": "Glasvormgeving",
    "jewellery.making": "Sieraden maken",
    "restoration.conservation": "Conservering",
    "restoration.repair": "Restauratieherstel",
    "stone.carving": "Steenhouwen",
    "leather.construction": "Lederbewerking",
  },
  pl: {
    "ceramics.wheel_throwing": "Toczenie na kole garncarskim",
    "ceramics.hand_building": "Ręczne formowanie",
    "ceramics.glazing": "Szkliwienie ceramiki",
    "ceramics.firing": "Wypał w piecu",
    "wood.joinery": "Połączenia stolarskie",
    "wood.carving": "Rzeźbienie w drewnie",
    "wood.furniture_making": "Meblarstwo",
    "textiles.weaving": "Tkactwo",
    "textiles.embroidery": "Haft",
    "textiles.sewing": "Szycie",
    "metal.smithing": "Kowalstwo",
    "metal.fabrication": "Obróbka metalu",
    "glass.forming": "Formowanie szkła",
    "jewellery.making": "Wytwarzanie biżuterii",
    "restoration.conservation": "Konserwacja",
    "restoration.repair": "Naprawa konserwatorska",
    "stone.carving": "Rzeźbienie w kamieniu",
    "leather.construction": "Wyroby ze skóry",
  },
  it: {
    "ceramics.wheel_throwing": "Lavorazione al tornio",
    "ceramics.hand_building": "Modellazione a mano",
    "ceramics.glazing": "Smaltatura ceramica",
    "ceramics.firing": "Cottura in forno",
    "wood.joinery": "Falegnameria e giunzioni",
    "wood.carving": "Intaglio del legno",
    "wood.furniture_making": "Produzione di mobili",
    "textiles.weaving": "Tessitura",
    "textiles.embroidery": "Ricamo",
    "textiles.sewing": "Cucito",
    "metal.smithing": "Forgiatura",
    "metal.fabrication": "Lavorazione del metallo",
    "glass.forming": "Formatura del vetro",
    "jewellery.making": "Creazione di gioielli",
    "restoration.conservation": "Conservazione",
    "restoration.repair": "Riparazione e restauro",
    "stone.carving": "Scultura su pietra",
    "leather.construction": "Lavorazione della pelle",
  },
  es: {
    "ceramics.wheel_throwing": "Torneado cerámico",
    "ceramics.hand_building": "Modelado a mano",
    "ceramics.glazing": "Esmaltado cerámico",
    "ceramics.firing": "Cocción en horno",
    "wood.joinery": "Ensamblaje de madera",
    "wood.carving": "Talla en madera",
    "wood.furniture_making": "Fabricación de muebles",
    "textiles.weaving": "Tejido",
    "textiles.embroidery": "Bordado",
    "textiles.sewing": "Costura",
    "metal.smithing": "Forja",
    "metal.fabrication": "Fabricación metálica",
    "glass.forming": "Conformado de vidrio",
    "jewellery.making": "Fabricación de joyería",
    "restoration.conservation": "Conservación",
    "restoration.repair": "Reparación y restauración",
    "stone.carving": "Talla en piedra",
    "leather.construction": "Trabajo en cuero",
  },
};

export function workspaceSkillLabel(
  locale: Locale,
  stableKey: string,
  labelEn: string,
  labelUk: string,
) {
  if (locale === "uk") return labelUk;
  if (locale === "en") return labelEn;
  return labels[locale]?.[stableKey] ?? labelEn;
}
