import type { Locale } from "@/lib/i18n";

const labels: Partial<Record<Locale, Record<string, string>>> = {
  fr: {
    "ceramics.wheel_throwing": "Tournage",
    "ceramics.hand_building": "Modelage à la main",
    "ceramics.glazing": "Émaillage",
    "ceramics.firing": "Cuisson",
    "wood.joinery": "Menuiserie",
    "wood.carving": "Sculpture sur bois",
    "wood.furniture_making": "Ébénisterie",
    "textiles.weaving": "Tissage",
    "textiles.embroidery": "Broderie",
    "textiles.sewing": "Couture",
    "metal.smithing": "Forge",
    "metal.fabrication": "Métallerie",
    "glass.forming": "Mise en forme du verre",
    "jewellery.making": "Bijouterie-joaillerie",
    "restoration.conservation": "Conservation",
    "restoration.repair": "Réparation-restauration",
    "stone.carving": "Taille de pierre",
    "leather.construction": "Maroquinerie",
  },
  de: {
    "ceramics.wheel_throwing": "Drehen an der Scheibe",
    "ceramics.hand_building": "Aufbautechnik",
    "ceramics.glazing": "Glasieren",
    "ceramics.firing": "Brennen",
    "wood.joinery": "Tischlerei",
    "wood.carving": "Holzschnitzen",
    "wood.furniture_making": "Möbelbau",
    "textiles.weaving": "Weben",
    "textiles.embroidery": "Sticken",
    "textiles.sewing": "Nähen",
    "metal.smithing": "Schmieden",
    "metal.fabrication": "Metallbau",
    "glass.forming": "Glasformung",
    "jewellery.making": "Schmuckherstellung",
    "restoration.conservation": "Konservierung",
    "restoration.repair": "Restauratorische Reparatur",
    "stone.carving": "Steinbildhauerei",
    "leather.construction": "Lederverarbeitung",
  },
  nl: {
    "ceramics.wheel_throwing": "Draaien",
    "ceramics.hand_building": "Opbouwtechniek",
    "ceramics.glazing": "Glazuren",
    "ceramics.firing": "Stoken",
    "wood.joinery": "Houtverbindingen",
    "wood.carving": "Houtsnijden",
    "wood.furniture_making": "Meubelmakerij",
    "textiles.weaving": "Weven",
    "textiles.embroidery": "Borduren",
    "textiles.sewing": "Naaien",
    "metal.smithing": "Smeden",
    "metal.fabrication": "Metaalbewerking",
    "glass.forming": "Glasvormgeving",
    "jewellery.making": "Edelsmeden",
    "restoration.conservation": "Conservering",
    "restoration.repair": "Restauratieherstel",
    "stone.carving": "Steenhouwen",
    "leather.construction": "Lederwaren maken",
  },
  pl: {
    "ceramics.wheel_throwing": "Toczenie na kole",
    "ceramics.hand_building": "Lepienie ręczne",
    "ceramics.glazing": "Szkliwienie ceramiki",
    "ceramics.firing": "Wypał w piecu",
    "wood.joinery": "Stolarstwo",
    "wood.carving": "Snycerstwo",
    "wood.furniture_making": "Meblarstwo",
    "textiles.weaving": "Tkactwo",
    "textiles.embroidery": "Haft",
    "textiles.sewing": "Szycie",
    "metal.smithing": "Kowalstwo",
    "metal.fabrication": "Ślusarstwo",
    "glass.forming": "Formowanie szkła",
    "jewellery.making": "Złotnictwo",
    "restoration.conservation": "Konserwacja",
    "restoration.repair": "Naprawa konserwatorska",
    "stone.carving": "Kamieniarstwo",
    "leather.construction": "Kaletnictwo",
  },
  it: {
    "ceramics.wheel_throwing": "Foggiatura al tornio",
    "ceramics.hand_building": "Foggiatura a mano",
    "ceramics.glazing": "Smaltatura ceramica",
    "ceramics.firing": "Cottura in forno",
    "wood.joinery": "Falegnameria",
    "wood.carving": "Intaglio del legno",
    "wood.furniture_making": "Costruzione di mobili",
    "textiles.weaving": "Tessitura",
    "textiles.embroidery": "Ricamo",
    "textiles.sewing": "Cucito",
    "metal.smithing": "Forgiatura",
    "metal.fabrication": "Carpenteria metallica",
    "glass.forming": "Formatura del vetro",
    "jewellery.making": "Oreficeria",
    "restoration.conservation": "Conservazione",
    "restoration.repair": "Riparazione e restauro",
    "stone.carving": "Scultura in pietra",
    "leather.construction": "Pelletteria",
  },
  es: {
    "ceramics.wheel_throwing": "Torneado",
    "ceramics.hand_building": "Modelado a mano",
    "ceramics.glazing": "Esmaltado cerámico",
    "ceramics.firing": "Cocción en horno",
    "wood.joinery": "Carpintería",
    "wood.carving": "Talla en madera",
    "wood.furniture_making": "Ebanistería",
    "textiles.weaving": "Tejido",
    "textiles.embroidery": "Bordado",
    "textiles.sewing": "Costura",
    "metal.smithing": "Forja",
    "metal.fabrication": "Metalistería",
    "glass.forming": "Conformado de vidrio",
    "jewellery.making": "Joyería",
    "restoration.conservation": "Conservación",
    "restoration.repair": "Reparación y restauración",
    "stone.carving": "Talla en piedra",
    "leather.construction": "Marroquinería",
  },
};

export function workspaceSkillLabel(
  locale: Locale,
  stableKey: string,
  labelEn: string,
  labelUk: string,
) {
  if (locale === "uk") return labelUk;
  if (locale === "en") return labelEn;
  return labels[locale]?.[stableKey] ?? labelEn;
}
