import type { Locale } from "@/lib/i18n";

type WorkspaceActionText = {
  invalidCraftIdType: string;
  newProfessional: string;
  newWorkshop: string;
  createdSelectFailed: string;
  closeConfirm: string;
  claimRequired: string;
  selectSkill: string;
  skillsNotFound: string;
  selectAnswer: string;
  evidenceRequired: string;
  addressCountryCode: string;
  exactPublicConsent: string;
  exactAddressRequired: string;
  displayNameRequired: string;
  countryCode: string;
  chooseImage: string;
  imageFormat: string;
  supportNoteLimit: string;
};

export const workspaceActionCopy: Record<Locale, WorkspaceActionText> = {
  en: {
    invalidCraftIdType: "Invalid CraftID type.",
    newProfessional: "New professional",
    newWorkshop: "New workshop",
    createdSelectFailed: "CraftID was created but the new record could not be selected.",
    closeConfirm: 'Type "close" to confirm account closure.',
    claimRequired: "Claim type and title are required.",
    selectSkill: "Choose at least one skill.",
    skillsNotFound: "Selected skills were not found.",
    selectAnswer: "Choose at least one answer.",
    evidenceRequired: "Title, evidence type and file are required.",
    addressCountryCode: "Address country code must contain 2 letters.",
    exactPublicConsent: "Confirm consent before publishing the full workshop address.",
    exactAddressRequired: "A public workshop address requires address line 1, locality and country code.",
    displayNameRequired: "Display name is required.",
    countryCode: "Country code must contain 2 letters.",
    chooseImage: "Choose an image.",
    imageFormat: "Use JPEG, PNG or WebP up to 5 MB.",
    supportNoteLimit: "Each category note must be 1000 characters or fewer.",
  },
  fr: {
    invalidCraftIdType: "Type de CraftID non valide.",
    newProfessional: "Nouveau professionnel",
    newWorkshop: "Nouvel atelier",
    createdSelectFailed: "Le CraftID a été créé, mais le nouveau dossier n’a pas pu être sélectionné.",
    closeConfirm: 'Tapez "close" pour confirmer la fermeture du compte.',
    claimRequired: "Le type et l’intitulé de la déclaration sont obligatoires.",
    selectSkill: "Sélectionnez au moins une compétence.",
    skillsNotFound: "Les compétences sélectionnées sont introuvables.",
    selectAnswer: "Choisissez au moins une réponse.",
    evidenceRequired: "Le titre, le type de preuve et le fichier sont obligatoires.",
    addressCountryCode: "Le code pays de l’adresse doit comporter 2 lettres.",
    exactPublicConsent: "Confirmez votre consentement avant de publier l’adresse complète de l’atelier.",
    exactAddressRequired: "Une adresse publique d’atelier nécessite l’adresse ligne 1, la localité et le code pays.",
    displayNameRequired: "Le nom affiché est obligatoire.",
    countryCode: "Le code pays doit comporter 2 lettres.",
    chooseImage: "Choisissez une image.",
    imageFormat: "Utilisez un fichier JPEG, PNG ou WebP de 5 Mo maximum.",
    supportNoteLimit: "La note de chaque catégorie doit contenir au maximum 1000 caractères.",
  },
  de: {
    invalidCraftIdType: "Ungültiger CraftID-Typ.",
    newProfessional: "Neue Fachperson",
    newWorkshop: "Neue Werkstatt",
    createdSelectFailed: "Die CraftID wurde erstellt, der neue Datensatz konnte jedoch nicht ausgewählt werden.",
    closeConfirm: 'Geben Sie "close" ein, um die Kontoschließung zu bestätigen.',
    claimRequired: "Art und Titel der Angabe sind erforderlich.",
    selectSkill: "Wählen Sie mindestens eine Kompetenz aus.",
    skillsNotFound: "Die ausgewählten Kompetenzen wurden nicht gefunden.",
    selectAnswer: "Wählen Sie mindestens eine Antwort aus.",
    evidenceRequired: "Titel, Nachweisart und Datei sind erforderlich.",
    addressCountryCode: "Der Ländercode der Adresse muss aus 2 Buchstaben bestehen.",
    exactPublicConsent: "Bestätigen Sie Ihre Zustimmung, bevor die vollständige Werkstattadresse veröffentlicht wird.",
    exactAddressRequired: "Für eine öffentliche Werkstattadresse sind Adresszeile 1, Ort und Ländercode erforderlich.",
    displayNameRequired: "Ein Anzeigename ist erforderlich.",
    countryCode: "Der Ländercode muss aus 2 Buchstaben bestehen.",
    chooseImage: "Wählen Sie ein Bild aus.",
    imageFormat: "Verwenden Sie JPEG, PNG oder WebP bis 5 MB.",
    supportNoteLimit: "Die Notiz je Kategorie darf höchstens 1000 Zeichen enthalten.",
  },
  nl: {
    invalidCraftIdType: "Ongeldig CraftID-type.",
    newProfessional: "Nieuwe professional",
    newWorkshop: "Nieuwe werkplaats",
    createdSelectFailed: "De CraftID is aangemaakt, maar het nieuwe dossier kon niet worden geselecteerd.",
    closeConfirm: 'Typ "close" om het sluiten van het account te bevestigen.',
    claimRequired: "Type en titel van de verklaring zijn verplicht.",
    selectSkill: "Kies ten minste één vaardigheid.",
    skillsNotFound: "De geselecteerde vaardigheden zijn niet gevonden.",
    selectAnswer: "Kies ten minste één antwoord.",
    evidenceRequired: "Titel, type bewijs en bestand zijn verplicht.",
    addressCountryCode: "De landcode van het adres moet uit 2 letters bestaan.",
    exactPublicConsent: "Bevestig uw toestemming voordat het volledige werkplaatsadres wordt gepubliceerd.",
    exactAddressRequired: "Een openbaar werkplaatsadres vereist adresregel 1, plaats en landcode.",
    displayNameRequired: "Een weergavenaam is verplicht.",
    countryCode: "De landcode moet uit 2 letters bestaan.",
    chooseImage: "Kies een afbeelding.",
    imageFormat: "Gebruik JPEG, PNG of WebP tot 5 MB.",
    supportNoteLimit: "De notitie per categorie mag maximaal 1000 tekens bevatten.",
  },
  pl: {
    invalidCraftIdType: "Nieprawidłowy typ CraftID.",
    newProfessional: "Nowy profesjonalista",
    newWorkshop: "Nowa pracownia",
    createdSelectFailed: "CraftID został utworzony, ale nie udało się wybrać nowego zapisu.",
    closeConfirm: 'Wpisz "close", aby potwierdzić zamknięcie konta.',
    claimRequired: "Typ i tytuł deklaracji są wymagane.",
    selectSkill: "Wybierz co najmniej jedną umiejętność.",
    skillsNotFound: "Nie znaleziono wybranych umiejętności.",
    selectAnswer: "Wybierz co najmniej jedną odpowiedź.",
    evidenceRequired: "Tytuł, typ dowodu i plik są wymagane.",
    addressCountryCode: "Kod kraju w adresie musi zawierać 2 litery.",
    exactPublicConsent: "Potwierdź zgodę przed opublikowaniem pełnego adresu pracowni.",
    exactAddressRequired: "Publiczny adres pracowni wymaga pierwszego wiersza adresu, miejscowości i kodu kraju.",
    displayNameRequired: "Nazwa wyświetlana jest wymagana.",
    countryCode: "Kod kraju musi zawierać 2 litery.",
    chooseImage: "Wybierz obraz.",
    imageFormat: "Użyj JPEG, PNG lub WebP o rozmiarze do 5 MB.",
    supportNoteLimit: "Notatka dla każdej kategorii może mieć maksymalnie 1000 znaków.",
  },
  it: {
    invalidCraftIdType: "Tipo di CraftID non valido.",
    newProfessional: "Nuovo professionista",
    newWorkshop: "Nuovo laboratorio",
    createdSelectFailed: "Il CraftID è stato creato, ma non è stato possibile selezionare il nuovo record.",
    closeConfirm: 'Digita "close" per confermare la chiusura dell’account.',
    claimRequired: "Tipo e titolo della dichiarazione sono obbligatori.",
    selectSkill: "Seleziona almeno una competenza.",
    skillsNotFound: "Le competenze selezionate non sono state trovate.",
    selectAnswer: "Scegli almeno una risposta.",
    evidenceRequired: "Titolo, tipo di evidenza e file sono obbligatori.",
    addressCountryCode: "Il codice paese dell’indirizzo deve contenere 2 lettere.",
    exactPublicConsent: "Conferma il consenso prima di pubblicare l’indirizzo completo del laboratorio.",
    exactAddressRequired: "Un indirizzo pubblico del laboratorio richiede riga indirizzo 1, località e codice paese.",
    displayNameRequired: "Il nome visualizzato è obbligatorio.",
    countryCode: "Il codice paese deve contenere 2 lettere.",
    chooseImage: "Scegli un’immagine.",
    imageFormat: "Usa JPEG, PNG o WebP fino a 5 MB.",
    supportNoteLimit: "La nota per ogni categoria deve contenere al massimo 1000 caratteri.",
  },
  es: {
    invalidCraftIdType: "Tipo de CraftID no válido.",
    newProfessional: "Nuevo profesional",
    newWorkshop: "Nuevo taller",
    createdSelectFailed: "El CraftID se creó, pero no se pudo seleccionar el nuevo registro.",
    closeConfirm: 'Escribe "close" para confirmar el cierre de la cuenta.',
    claimRequired: "El tipo y el título de la declaración son obligatorios.",
    selectSkill: "Elige al menos una competencia.",
    skillsNotFound: "No se encontraron las competencias seleccionadas.",
    selectAnswer: "Elige al menos una respuesta.",
    evidenceRequired: "El título, el tipo de evidencia y el archivo son obligatorios.",
    addressCountryCode: "El código de país de la dirección debe contener 2 letras.",
    exactPublicConsent: "Confirma tu consentimiento antes de publicar la dirección completa del taller.",
    exactAddressRequired: "Una dirección pública del taller requiere línea de dirección 1, localidad y código de país.",
    displayNameRequired: "El nombre visible es obligatorio.",
    countryCode: "El código de país debe contener 2 letras.",
    chooseImage: "Elige una imagen.",
    imageFormat: "Utiliza JPEG, PNG o WebP de hasta 5 MB.",
    supportNoteLimit: "La nota de cada categoría debe tener como máximo 1000 caracteres.",
  },
  uk: {
    invalidCraftIdType: "Невірний тип CraftID.",
    newProfessional: "Новий професіонал",
    newWorkshop: "Нова майстерня",
    createdSelectFailed: "CraftID створено, але новий запис не вдалося вибрати.",
    closeConfirm: "Введіть «закрити», щоб підтвердити закриття облікового запису.",
    claimRequired: "Потрібно вказати тип і назву твердження.",
    selectSkill: "Оберіть щонайменше одну навичку.",
    skillsNotFound: "Вибрані навички не знайдено.",
    selectAnswer: "Оберіть хоча б одну відповідь.",
    evidenceRequired: "Потрібно вказати назву, тип доказу та файл.",
    addressCountryCode: "Код країни адреси має містити 2 літери.",
    exactPublicConsent: "Підтвердьте згоду на публікацію повної адреси майстерні.",
    exactAddressRequired: "Для публічної адреси потрібні адреса, населений пункт і код країни.",
    displayNameRequired: "Потрібно вказати відображуване ім’я.",
    countryCode: "Код країни має містити 2 літери.",
    chooseImage: "Оберіть зображення.",
    imageFormat: "Дозволені JPEG, PNG або WebP до 5 МБ.",
    supportNoteLimit: "Пояснення для кожної категорії має містити не більше 1000 символів.",
  },
};
